security:
    encoders:
        DWES\farmanagerBundle\Entity\Usuario:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_REGISTRADO]
        ROLE_SUPER_ADMIN: [ROLE_REGISTRADO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]

        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        user_db:
            entity: { class: DWESfarmanagerBundle:Usuario, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        dwes_blog_area_protegida:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /user
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true


    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: [ROLE_REGISTRADO] }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
